# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Consensual Software"
description: > # this means to ignore newlines until "email:"
   Where Consent and Software Design Intersect

email: hi@consensualsoftware.com
#blog logo to be changed
logo: "/assets/images/cs_logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Danielle & Lucas'
author: 'Danielle & Lucas'
author_image: "/assets/images/author.jpg" # should be added

paginate:	5

url: "http://consensualsoftware.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@consentsoftware'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

#### social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/@consentsoftware

  - icon:	github
    url:	https://github.com/consensualsoftware/consensual_software
